name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 2.7
  - basemap = 1.0.7
  - matplotlib = 1.5.1
  - numpy
  - unicodecsv
  - scipy
  - pandas
  - pip:
    - datetime
    - nbconvert
