name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - numpy
  - unicodecsv
  - scipy
  - pandas
  - pip:
    - matplotlib
    - datetime
    - nbconvert
    - urllib
    - basemap
