name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap = 1.0.8
  - matplotlib = 1.5.1
  - numpy = 1.11.1
  - unicodecsv = 0.14.1
  - scipy = 0.17.1
  - pandas = 0.19.0
  - pip:
    - datetime
    - nbconvert = 4.2.0
